FROM golang:1.19

RUN apt-get update && apt-get install -y --no-install-recommends \
        gettext-base \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /...

ENV GO111MODULE=on

RUN apt-get -y update && apt-get -y install jq curl

RUN download_url=$(curl -s https://api.github.com/repos/go-swagger/go-swagger/releases/latest | \
      jq -r '.assets[] | select(.name | contains("'"$(uname | tr '[:upper:]' '[:lower:]')"'_amd64")) | .browser_download_url') \
      && curl -o /usr/local/bin/swagger -L'#' "$download_url" \
      && chmod +x /usr/local/bin/swagger

RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest \
    && go install golang.org/x/tools/cmd/goimports@latest

RUN CGO_ENABLED=0

ARG DEVELOPER

